### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by fidiego** [Trackvia/API-Python-SDK#6]
### Description
I'm attempting to initialize the trackvia client 

### Install Method
pipenv install -e git+https://github.com/Trackvia/API-Python-SDK.git#egg=trackvia

### Environment
python --version
> Python 3.7.2

OS
> OS X

<details>
<summary>
Stacktrace
</summary>

<pre>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-5700a6ce7d46> in <module>
----> 1 tv_client = trackvia.trackvia('[secret]', '[secret]', '[secret]', [secret])

~/.local/share/virtualenvs/application-_hNEXKaa/src/trackvia/trackvia/__init__.py in __init__(self, url, username, password, apikey)                                                
     29                 if values['username'] is not None and values['password'] is not None:                                                                                       
     30                         #Actually do the login and parse the token from the response.                                                                                       
---> 31                         resp,body=self.__json_request("{0}/oauth/token".format(self.base_url),post=values)                                                                  
     32
     33                         self.token=body['value']

~/.local/share/virtualenvs/application-_hNEXKaa/src/trackvia/trackvia/__init__.py in __json_request(self, url, type, post, get, content_type)                                       
     72
     73                 h = httplib2.Http()
---> 74                 response, content = h.request(url+get_data,type,headers=headers,body=post_data)                                                                             
     75
     76                 try:

~/.local/share/virtualenvs/application-_hNEXKaa/lib/python3.7/site-packages/httplib2/__init__.py in request(self, uri, method, body, headers, redirections, connection_type)        
   1922                         headers,
   1923                         redirections,
-> 1924                         cachekey,
   1925                     )
   1926         except Exception as e:

~/.local/share/virtualenvs/application-_hNEXKaa/lib/python3.7/site-packages/httplib2/__init__.py in _request(self, conn, host, absolute_uri, request_uri, method, body, headers, redirections, cachekey)
   1593
   1594         (response, content) = self._conn_request(
-> 1595             conn, request_uri, method, body, headers
   1596         )
   1597

~/.local/share/virtualenvs/application-_hNEXKaa/lib/python3.7/site-packages/httplib2/__init__.py in _conn_request(self, conn, request_uri, method, body, headers)                   
   1500                 if conn.sock is None:
   1501                     conn.connect()
-> 1502                 conn.request(method, request_uri, body, headers)
   1503             except socket.timeout:
   1504                 conn.close()

/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py in request(self, method, url, body, headers, encode_chunked)                 
   1227                 encode_chunked=False):
   1228         """Send a complete request to the server."""
-> 1229         self._send_request(method, url, body, headers, encode_chunked)
   1230
   1231     def _send_request(self, method, url, body, headers, encode_chunked):

/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)           
   1273             # default charset of iso-8859-1.
   1274             body = _encode(body, 'body')
-> 1275         self.endheaders(body, encode_chunked=encode_chunked)
   1276
   1277     def getresponse(self):

/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py in endheaders(self, message_body, encode_chunked)                            
   1222         else:
   1223             raise CannotSendHeader()
-> 1224         self._send_output(message_body, encode_chunked=encode_chunked)
   1225
   1226     def request(self, method, url, body=None, headers={}, *,

/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py in _send_output(self, message_body, encode_chunked)                          
   1052                     # chunked encoding
   1053                     chunk = f'{len(chunk):X}\r\n'.encode('ascii') + chunk \
-> 1054                         + b'\r\n'
   1055                 self.send(chunk)
   1056

TypeError: can't concat str to bytes
</pre>

</details>

**Comment by mscherer11** [comment]
@fidiego As per https://github.com/Trackvia/API-Python-SDK/blob/master/setup.py#L50, this SDK is setup for Python 2. Please let us know if this persists after you switch your environment. I'll reopen if it is still a problem

**Comment by fidiego** [comment]
@mscherer11 

Noted. My environment is python3 so I've opted for implementing the endpoints I need in a python3 client instead. Thanks for the response.
